apiVersion: 1

datasources:
  - name: BattDB
    type: postgres
    url: postgres:5432
    database: battdb
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
